version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13
    environment:
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
    steps:
      - checkout
      - run:
          name: Install OpenJDK
          command: |
            sudo apt-get update
            sudo apt-get install openjdk-8-jdk
      - run:
          name: install firebase-tools
          command: sudo npm install firebase-tools -g
      - run:
          name: install firestore emulator
          command: firebase setup:emulators:firestore
      - run:
          name: run firestore emulator
          # command: firebase serve --only firestore
          # https://stackoverflow.com/questions/54274835/firestore-emulator-fails-to-start-when-run-inside-docker
          command: java -jar $HOME/.cache/firebase/emulators/cloud-firestore-emulator-v1.5.0.jar --host=127.0.0.1
          background: true
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm install for functions
          command: |
            cd functions
            npm install
      - run:
          name: firestore test
          command: npm run mocha
      #- run:
      #    name: build
      #    command: npm run build
      #- run:
      #    name: deploy to Firebase Hosting
      #    command:  firebase deploy --token=$FIREBASE_TOKEN
